name: Deploy via SSH

on:
  push:
    branches:
      - main

permissions: {}

env:
  SSH_TARGET: 'deploy@fedproxy.com'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        persist-credentials: false

    - name: Install opkssh
      run: curl -sSLf https://raw.githubusercontent.com/openpubkey/opkssh/main/scripts/install-linux.sh | sudo bash

    - name: Login
      run: opkssh login github

    - name: Check connection
      run: |
        ssh -o StrictHostKeyChecking=accept-new "${SSH_TARGET}" "echo 'Hello from GitHub Actions'"

    - name: SSH runner helper
      shell: cp {0} run-via-ssh.sh
      run: |
        set -xeuo pipefail
        ssh -o StrictHostKeyChecking=accept-new "${SSH_TARGET}" bash -xe < "${1}"

    - name: Run commands on runner
      run: |
        hostname
        ip a

    - name: Run commands on server
      shell: bash -e run-via-ssh.sh {0}
      run: |
        hostname
        ip a
