name: Deploy via SSH

on:
  push:
    branches:
      - main

permissions: {}

env:
  SSH_TARGET: 'deploy@fedproxy.com'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        persist-credentials: false

    - uses: actions/setup-go@v6
      with:
        go-version: '1.26'

    - name: Build golang
      run: |
        cd src/golang/
        mkdir -p target
        go build -o target/atprp-ssh-relay ./cmd/atprp-ssh-relay/main.go

    - name: Install opkssh
      run: curl -sSLf https://raw.githubusercontent.com/openpubkey/opkssh/main/scripts/install-linux.sh | sudo bash

    - name: Login
      run: opkssh login github

    - name: SSH runner helper
      shell: cp {0} run-via-ssh.sh
      run: |
        set -xeuo pipefail
        ssh -i /.ssh/id_ecdsa -o StrictHostKeyChecking=accept-new "${SSH_TARGET}" bash -xe < "${1}"

    - name: Run commands on server
      shell: bash -e run-via-ssh.sh {0}
      run: |
        sudo apt-get update
        sudo apt-get install -y caddy
        rm -rf /tmp/stage
        rm -rf /tmp/fedproxy-ssh-public-keys
        mkdir -p /tmp/stage

    - name: Copy over files
      run: |
        scp -r -i /.ssh/id_ecdsa -o StrictHostKeyChecking=accept-new src/javascript/fedproxy-ssh-public-keys "${SSH_TARGET}":/tmp/
        scp -i /.ssh/id_ecdsa -o StrictHostKeyChecking=accept-new src/golang/Caddyfile "${SSH_TARGET}":/tmp/stage/Caddyfile
        scp -i /.ssh/id_ecdsa -o StrictHostKeyChecking=accept-new src/golang/target/atprp-ssh-relay "${SSH_TARGET}":/tmp/stage/atprp-ssh-relay

    - name: Run commands on server
      shell: bash -e run-via-ssh.sh {0}
      run: |
        sudo rm -rf /var/www/html
        sudo mkdir -pv /var/www/
        sudo mkdir -pv /opt/caddy
        sudo chown -R caddy:caddy /opt/caddy

        sudo mv /tmp/fedproxy-ssh-public-keys /var/www/html
        sudo mv /tmp/stage/Caddyfile /etc/caddy/Caddyfile
        sudo mv /tmp/stage/atprp-ssh-relay /usr/bin/atprp-ssh-relay
        sudo systemctl daemon-reload
        sudo systemctl enable --now caddy
        sudo systemctl reload caddy

        sudo tee /etc/systemd/system/atprp-ssh-relay.service > /dev/null <<'EOF'
        [Unit]
        Description=atprp-ssh-relay
        After=network.target caddy.service
        Wants=caddy.service
        [Service]
        Type=simple
        ExecStart=/usr/bin/atprp-ssh-relay
        Restart=on-failure
        Environment=THIS_ENDPOINT=fedproxy.com
        Environment=CADDY_SOCK=/opt/caddy/caddy-admin.sock
        WorkingDirectory=/var/run
        RestartSec=5

        [Install]
        WantedBy=multi-user.target
        EOF

        sudo systemctl daemon-reload
        sudo systemctl enable --now atprp-ssh-relay.service
        sudo systemctl status --no-pager atprp-ssh-relay.service

        sudo sed -n '1,200p' /usr/lib/systemd/system/caddy.service >/tmp/caddy.service.tmp
        sudo sed -i '/^User=/d; /^Group=/d; /^PrivateTmp=/d; /^ProtectSystem=/d' /tmp/caddy.service.tmp
        sudo sed -i '1iUser=root\nGroup=root\nPrivateTmp=no\nProtectSystem=off' /tmp/caddy.service.tmp
        sudo install -m644 /tmp/caddy.service.tmp /usr/lib/systemd/system/caddy.service
        sudo systemctl daemon-reload
        sudo systemctl restart caddy.service
